'use strict';

const crawler = new RegExp('vkshare|slackbot|whatsapp|linkedinbot|googlebot|odklbot|facebot|yahoo|bingbot|baiduspider|yandex|yeti|yodaobot|gigabot|ia_archiver|facebookexternalhit|twitterbot|WpLync|iPadLync|AndroidLync|iPhoneLync|SkypeUriPreview', 'i');
const partner = new RegExp('^p=[0-9]+');

const redirResponse = {status: '301', statusDescription: 'Moved Permanently', headers: {location: [{key: 'Location', value: 'https://www.bonusway.fi'}]}};
const splitDomainName = 'reverse-proxy-1450841031.eu-west-1.elb.amazonaws.com';

exports.handler = (event, context, callback) => {
  const request = event.Records[0].cf.request;
  
  // bonusway.fi -> www.bonusway.fi
  if (request.headers.host[0].value == 'bonusway.fi') {
  	  let uri = 'https://www.bonusway.fi' + request.uri;
  	  if (typeof request.querystring != 'undefined' && request.querystring && request.querystring.length > 0)
  		uri += '?' + request.querystring;
      redirResponse.headers.location[0].value = uri;
      callback(null, redirResponse);
      return;
  }
  
  // USER-SET COOKIE -> old site
  if (typeof request.headers.cookie != 'undefined') {
    for (let i = 0; i < request.headers.cookie.length; i++) {
      if (request.headers.cookie[i].value.indexOf('siteUsed=old') >= 0) {
        request.headers.host[0].value = 'www.bonusway.fi';
        request.origin = {
            custom: {
                domainName: splitDomainName,
                port: 443,
                protocol: 'https',
                path: '',
                sslProtocols: ['TLSv1', 'TLSv1.1', 'TLSv1.2'],
                readTimeout: 5,
                keepaliveTimeout: 5,
                customHeaders: {}
            }
        };
        callback(null, request);
        return;
      }
    }
  }

  // PARTNER URLS -> old site
  if (typeof request.querystring != 'undefined' && request.querystring && partner.test(request.querystring)) {
    request.headers.host[0].value = 'www.bonusway.fi';
    request.origin = {
        custom: {
            domainName: splitDomainName,
            port: 443,
            protocol: 'https',
            path: '',
            sslProtocols: ['TLSv1', 'TLSv1.1', 'TLSv1.2'],
            readTimeout: 5,
            keepaliveTimeout: 5,
            customHeaders: {}
        }
    };
    callback(null, request);
    return;
  }
  
  // PREDEFINED REDIRECTS
  let redirects = [
  	{'source': '^/reset-password/(.+)$', 'destination': 'https://www.bonusway.fi/auth/luo-salasana/$1'},
  	{'source': '^/email-preferences/(.+)$', 'destination': 'https://www.bonusway.fi/sahkopostien-tilaukset/$1'},
  	{'source': '^/boost-activation/(.+)$', 'destination': 'https://www.bonusway.fi/aktivoi-bonuskerroin/$1'},
  	{'source': '^/boost/(.+?)/(.+)$', 'destination': 'https://www.bonusway.fi/bonuskerroin/$1/$2'},
  	{'source': '^/trending$', 'destination': 'https://www.bonusway.fi/diilit/kaikki/kaikki/trendaamassa'},
  	{'source': '^/testimonial/users$', 'destination': 'https://www.bonusway.fi/kokemukset'},
  	{'source': '^/testimonials$', 'destination': 'https://www.bonusway.fi/kokemukset'},
  	{'source': '^/public-profile/(.+)$', 'destination': 'https://www.bonusway.fi/kayttajat/$1/kayttaja'},
  	{'source': '^/collection/(.+)$', 'destination': 'https://www.bonusway.fi/kokoelmat/$1/kokoelma'},
  	{'source': '^/promotions/(.+)$', 'destination': 'https://www.bonusway.fi/diilit/diili/$1/kommentit'},
  	{'source': '^/offer/(.+)\\?section=sale$', 'destination': 'https://www.bonusway.fi/diilit/$1/diili'},
  	{'source': '^/offer/(.+)$', 'destination': 'https://www.bonusway.fi/diilit/$1/diili'},
  	{'source': '^/offer$', 'destination': 'https://www.bonusway.fi/diilit'},
  	{'source': '^/offer\\?section=themes$', 'destination': 'https://www.bonusway.fi/diilit/kokoelmat'},
  	{'source': '^/offer\\?section=sale$', 'destination': 'https://www.bonusway.fi/diilit/kaikki/alennukset/viimeisimmat'},
  	{'source': '^/offer\\?section=sale&sort=creation$', 'destination': 'https://www.bonusway.fi/diilit/kaikki/alennukset/viimeisimmat'},
  	{'source': '^/offer\\?section=promocode$', 'destination': 'https://www.bonusway.fi/diilit/kaikki/alekoodit/viimeisimmat'},
  	{'source': '^/offer\\?section=promocode&sort=creation$', 'destination': 'https://www.bonusway.fi/diilit/kaikki/alekoodit/viimeisimmat'},
  	{'source': '^/offer\\?section=increasedbonus$', 'destination': 'https://www.bonusway.fi/diilit/kaikki/korotettu-bonus/viimeisimmat'},
  	{'source': '^/offer\\?section=increasedbonus&sort=creation$', 'destination': 'https://www.bonusway.fi/diilit/kaikki/korotettu-bonus/viimeisimmat'},
  	{'source': '^/offer\\?section=user$', 'destination': 'https://www.bonusway.fi/diilit/kaikki/kayttajilta/viimeisimmat'},
  	{'source': '^/offer\\?section=user&sort=creation$', 'destination': 'https://www.bonusway.fi/diilit/kaikki/kayttajilta/viimeisimmat'},
  	{'source': '^/stores/(.+?)/(.+)$', 'destination': 'https://www.bonusway.fi/verkkokaupat/$2/$1'},
  	{'source': '^/stores$', 'destination': 'https://www.bonusway.fi/verkkokaupat'},
  	{'source': '^/stores\\?sort=popularity&category=99999&limit=10$', 'destination': 'https://www.bonusway.fi/verkkokaupat/kaikki/suosituimmat'},
  	{'source': '^/stores\\?sort=trending&category=99999&limit=10$', 'destination': 'https://www.bonusway.fi/verkkokaupat/kaikki/trendaavat'},
  	{'source': '^/stores\\?sort=name&category=20000&limit=10&subcategory=20000$', 'destination': 'https://www.bonusway.fi/verkkokaupat/muoti/a-z'},
  	{'source': '^/stores\\?sort=bonus&category=20000&limit=10&subcategory=20000&unit=percentage$', 'destination': 'https://www.bonusway.fi/verkkokaupat/muoti/korkein-bonus-per'},
  	{'source': '^/waiting/offer/([0-9]+)/([0-9]+)/([0-9]+)', 'destination': 'https://www.bonusway.fi/odota?userid=$1&campaignid=$2&offerid=$3'},
  	{'source': '^/waiting/([0-9]+)/([0-9]+)/([0-9]+)', 'destination': 'https://www.bonusway.fi/odota?userid=$1&campaignid=$2&offerid=$3'},
  	{'source': '^/waiting/([0-9]+)/([0-9]+)', 'destination': 'https://www.bonusway.fi/odota?userid=$1&campaignid=$2'},
  	{'source': '^//waiting/([0-9]+)/([0-9]+)', 'destination': 'https://www.bonusway.fi/odota?userid=$1&campaignid=$2'},
  	{'source': '^/refer-friend$', 'destination': 'https://www.bonusway.fi/kutsu-kaverisi'},
  	{'source': '^/kerro-kaverille$', 'destination': 'https://tuki.bonusway.fi/kutsu-kaverisi-ohjelma/'},
  	{'source': '^/settings$', 'destination': 'https://www.bonusway.fi/asetukset/julkinen'},
  	{'source': '^/my-bonus$', 'destination': 'https://www.bonusway.fi/bonukset/arvioitavana'},
  	{'source': '^/lisaosa$', 'destination': 'https://tuki.bonusway.fi/selainlisaosa/'},
  	{'source': '^/mobiilisovellus$', 'destination': 'https://tuki.bonusway.fi/mobiilisovellus/'},
  	{'source': '^/tietoa/kayttoehdot$', 'destination': 'https://tuki.bonusway.fi/kayttoehdot/'},
  	{'source': '^/information/terms-and-conditions$', 'destination': 'https://tuki.bonusway.fi/kayttoehdot/'},
  	{'source': '^/tietoa/markkinointi$', 'destination': 'https://tuki.bonusway.fi/tietoa-markkinoinnista/'},
  	{'source': '^/tietoa/usein-kysytyt-kysymykset$', 'destination': 'https://tuki.bonusway.fi/'},
  	{'source': '^/tietoa/opas$', 'destination': 'https://tuki.bonusway.fi/opas/'},
  	{'source': '^/tietoa/miten-ostohyvitys-toimii$', 'destination': 'https://tuki.bonusway.fi/miten-bonusway-toimii/'},
  	{'source': '^/tietoa/yhteystiedot$', 'destination': 'https://tuki.bonusway.fi/yhteystiedot/'},
  	{'source': '^/tietoa/tietoa$', 'destination': 'https://tuki.bonusway.fi/tietoa-meista/'},
  	{'source': '^/tietoa/rekisteriseloste$', 'destination': 'https://tuki.bonusway.fi/tietosuojaseloste/'},
  	{'source': '^/tietoa/markkinointiyhteistyo$', 'destination': 'https://tuki.bonusway.fi/tietoa-partnereille/'},
  	{'source': '^/tietoa/tyopaikat', 'destination': 'https://tuki.bonusway.fi/yhteystiedot/'},
  	{'source': '^/tietoa/tietoa-verkkokaupoille$', 'destination': 'https://tuki.bonusway.fi/tietoa-verkkokaupoille/'},
	{'source': '^/public-profile$', 'destination': 'https://www.bonusway.fi/'},
  	{'source': '^/\\?dl=(.+)$', 'destination': 'https://www.bonusway.fi/deeplinks/$1'},
   	{'source': '^/deep-link/(.+)$', 'destination': 'https://www.bonusway.fi/deeplinks/$1'},
  	{'source': '^/brand/.+$', 'destination': 'https://www.bonusway.fi/diilit'},
  	{'source': '^/brand$', 'destination': 'https://www.bonusway.fi/diilit'},
  	{'source': '^/home$', 'destination': 'https://www.bonusway.fi/'},
  ];
  for (let i = 0; i < redirects.length; i++) {
  	let source = new RegExp(redirects[i].source);
  	let matches = request.uri.match(source);
    if (matches && matches.length > 0) {
    	let destination = redirects[i].destination;
      for (let i = 1; i < matches.length; i++) {
      	destination = destination.replace('$' + i, matches[i]);
      }
      redirResponse.headers.location[0].value = destination;
      callback(null, redirResponse);
      return;
    }
  }
  
  // PREDEFINED OLD SITE URLS
  let oldSiteUris = [
	{'source': '^/testi123456$'},
	{'source': '^/10$'},
	{'source': '^/100yotakesaan$'},
	{'source': '^/10e$'},
	{'source': '^/10etarjous$'},
	{'source': '^/10euroa$'},
	{'source': '^/10lisatarjous$'},
	{'source': '^/10mass$'},
	{'source': '^/5ebonus$'},
	{'source': '^/5etarjous$'},
	{'source': '^/aamihh$'},
	{'source': '^/adlibris-bonus$'},
	{'source': '^/afshin$'},
	{'source': '^/agm$'},
	{'source': '^/ainonblogi$'},
	{'source': '^/ainov$'},
	{'source': '^/alennus-ja-suklaa$'},
	{'source': '^/alennuskoodi-ja-suklaa$'},
	{'source': '^/alennuskoodit$'},
	{'source': '^/alennuskoodit-muoti$'},
	{'source': '^/alennuskoodit-sisustus$'},
	{'source': '^/alennuskooditus$'},
	{'source': '^/alennusmyynnit$'},
	{'source': '^/aliexpress-bonus$'},
	{'source': '^/alittlebitdramatic$'},
	{'source': '^/amino$'},
	{'source': '^/angata$'},
	{'source': '^/annajasebastian$'},
	{'source': '^/annakoo$'},
	{'source': '^/annaliina$'},
	{'source': '^/annis$'},
	{'source': '^/anssivaittinen$'},
	{'source': '^/armoaisille$'},
	{'source': '^/askingfortrouble$'},
	{'source': '^/asos-bonus$'},
	{'source': '^/asuste$'},
	{'source': '^/autot-ja-varaosat$'},
	{'source': '^/autre$'},
	{'source': '^/bailaamaan$'},
	{'source': '^/banggood-bonus$'},
	{'source': '^/birthday-test$'},
	{'source': '^/blackfriday2016$'},
	{'source': '^/blogi-aliexpress-0117$'},
	{'source': '^/blogi-matkamessut-0117$'},
	{'source': '^/blogit2016$'},
	{'source': '^/bonukset-rahana$'},
	{'source': '^/bonus$'},
	{'source': '^/bonus-vanha$'},
	{'source': '^/bonustanetista$'},
	{'source': '^/bonusway-blogi$'},
	{'source': '^/booking-bonus$'},
	{'source': '^/boozttarjous$'},
	{'source': '^/bubbleroom-bonus$'},
	{'source': '^/bussi$'},
	{'source': '^/buzzador$'},
	{'source': '^/by-selma$'},
	{'source': '^/byselma$'},
	{'source': '^/cardu$'},
	{'source': '^/ccandyysblog$'},
	{'source': '^/cdon$'},
	{'source': '^/cdontarjous$'},
	{'source': '^/cirkusjoanna$'},
	{'source': '^/cityshoppari$'},
	{'source': '^/cityshoppari2017$'},
	{'source': '^/clientop$'},
	{'source': '^/colourme$'},
	{'source': '^/concoction$'},
	{'source': '^/currencysymbolshort$'},
	{'source': '^/currencysymbolslider$'},
	{'source': '^/denise$'},
	{'source': '^/derya$'},
	{'source': '^/didem$'},
	{'source': '^/digisivu$'},
	{'source': '^/digisivu2$'},
	{'source': '^/diili$'},
	{'source': '^/discshop-bonus$'},
	{'source': '^/downshiftaus$'},
	{'source': '^/ebookers-tarjous$'},
	{'source': '^/ebookerstarjous$'},
	{'source': '^/edullisempianettiostoksia$'},
	{'source': '^/edutjavoitot$'},
	{'source': '^/eerika$'},
	{'source': '^/eevsku$'},
	{'source': '^/eforeeva$'},
	{'source': '^/egentic$'},
	{'source': '^/elaenemman$'},
	{'source': '^/elinatervo$'},
	{'source': '^/elisa$'},
	{'source': '^/elisa-malik$'},
	{'source': '^/ellostarjous$'},
	{'source': '^/emminjaterhin$'},
	{'source': '^/endorfiinikoukussa$'},
	{'source': '^/erikoiset$'},
	{'source': '^/escapefromreality$'},
	{'source': '^/essimaaninka$'},
	{'source': '^/et$'},
	{'source': '^/etu10$'},
	{'source': '^/etusivu$'},
	{'source': '^/expedia-bonus$'},
	{'source': '^/facebook$'},
	{'source': '^/facebook-kampanja$'},
	{'source': '^/facebook2$'},
	{'source': '^/facebookohlok$'},
	{'source': '^/facebookohlok2$'},
	{'source': '^/facediili$'},
	{'source': '^/fashion$'},
	{'source': '^/fb-kokit$'},
	{'source': '^/finavia$'},
	{'source': '^/finavia-vanha$'},
	{'source': '^/finnairplus$'},
	{'source': '^/fitnesstukkutarjous$'},
	{'source': '^/fitoona$'},
	{'source': '^/focusonfavorites$'},
	{'source': '^/frank$'},
	{'source': '^/freelancerfashion$'},
	{'source': '^/ft$'},
	{'source': '^/ft10$'},
	{'source': '^/glyffi$'},
	{'source': '^/go4itvol2$'},
	{'source': '^/grilli$'},
	{'source': '^/haamessut$'},
	{'source': '^/haamessut3$'},
	{'source': '^/haatjajuhlat$'},
	{'source': '^/hamk$'},
	{'source': '^/harmaakorva$'},
	{'source': '^/helga$'},
	{'source': '^/hintaseuranta$'},
	{'source': '^/hintaseuranta-tarjous$'},
	{'source': '^/hintaseuranta2$'},
	{'source': '^/hintofluxury$'},
	{'source': '^/homevialaura$'},
	{'source': '^/homewhitehome$'},
	{'source': '^/hope$'},
	{'source': '^/hopottajat$'},
	{'source': '^/hotellibonus$'},
	{'source': '^/hotellioista-bonusta$'},
	{'source': '^/hotels$'},
	{'source': '^/hotelscomtarjous$'},
	{'source': '^/huippuedut$'},
	{'source': '^/huono-aiti$'},
	{'source': '^/huutonet$'},
	{'source': '^/hyvaterveys$'},
	{'source': '^/idaamanda$'},
	{'source': '^/idajemina$'},
	{'source': '^/idajemina4646$'},
	{'source': '^/iinaps$'},
	{'source': '^/ilmainen-jaatelo$'},
	{'source': '^/ilmainenpizza$'},
	{'source': '^/ilmainensuklaalevy$'},
	{'source': '^/ilmaistarjoukset$'},
	{'source': '^/ilmoituspalsta$'},
	{'source': '^/ilonajulia$'},
	{'source': '^/ilonaworks$'},
	{'source': '^/indiedays$'},
	{'source': '^/insolo$'},
	{'source': '^/irc-galleria$'},
	{'source': '^/is$'},
	{'source': '^/isanpaiva2016$'},
	{'source': '^/jane$'},
	{'source': '^/jasminsofi$'},
	{'source': '^/jkl$'},
	{'source': '^/jkokki$'},
	{'source': '^/jmorethanwords$'},
	{'source': '^/joanna$'},
	{'source': '^/jonnamatikainen$'},
	{'source': '^/joulu$'},
	{'source': '^/joulukampanja$'},
	{'source': '^/joululahjat$'},
	{'source': '^/julia-jokiniemi$'},
	{'source': '^/juliatoivola$'},
	{'source': '^/karkkipaiva$'},
	{'source': '^/karostardust$'},
	{'source': '^/kauneus-terveys$'},
	{'source': '^/kaveri$'},
	{'source': '^/kehonrakennusjafitness$'},
	{'source': '^/kengat-edullisesti$'},
	{'source': '^/kerrokaverille$'},
	{'source': '^/kerttumatilda$'},
	{'source': '^/kesa$'},
	{'source': '^/kesakampanja$'},
	{'source': '^/kestavyysurheilu$'},
	{'source': '^/kiinakaupat$'},
	{'source': '^/kiinalaisetkaupat$'},
	{'source': '^/kimppadiili$'},
	{'source': '^/kirjat-edullisemmin$'},
	{'source': '^/kitsastelija$'},
	{'source': '^/kitupiikki$'},
	{'source': '^/klaani$'},
	{'source': '^/klipsiworld$'},
	{'source': '^/klipsiworld-yp$'},
	{'source': '^/km$'},
	{'source': '^/kodinkuvalehti$'},
	{'source': '^/koirakaverit$'},
	{'source': '^/kt-traiding-tarjous$'},
	{'source': '^/kyamk$'},
	{'source': '^/kysely$'},
	{'source': '^/lahjakortti231267$'},
	{'source': '^/lahjakorttitarjous$'},
	{'source': '^/laivamatkoista$'},
	{'source': '^/lamko$'},
	{'source': '^/lapinyliopisto$'},
	{'source': '^/lasimestari$'},
	{'source': '^/lastentarvikkeet$'},
	{'source': '^/lateksituppii$'},
	{'source': '^/laurakinterior$'},
	{'source': '^/lauraojala$'},
	{'source': '^/laurrenna$'},
	{'source': '^/leffa$'},
	{'source': '^/lehtikuningastarjous$'},
	{'source': '^/lekmertarjous$'},
	{'source': '^/lennoista-bonusta$'},
	{'source': '^/lensontarjous$'},
	{'source': '^/liangtest$'},
	{'source': '^/liangtestshort$'},
	{'source': '^/liangtestslider$'},
	{'source': '^/lifeofsilja$'},
	{'source': '^/lifestyleostos$'},
	{'source': '^/liikematkaaja$'},
	{'source': '^/liiku-edullisemmin$'},
	{'source': '^/liittymisetu$'},
	{'source': '^/liity$'},
	{'source': '^/liity-heti$'},
	{'source': '^/liity-ilmaiseksi$'},
	{'source': '^/liity-nyt$'},
	{'source': '^/lindamanuella$'},
	{'source': '^/lindamanuella15$'},
	{'source': '^/livelife$'},
	{'source': '^/maattahanna$'},
	{'source': '^/majoitus-edullisesti$'},
	{'source': '^/mamablogit$'},
	{'source': '^/mandiolivia$'},
	{'source': '^/marakatti$'},
	{'source': '^/mariannesendenali$'},
	{'source': '^/mariieveronica$'},
	{'source': '^/martinaaitolehti$'},
	{'source': '^/mass10$'},
	{'source': '^/matildannas$'},
	{'source': '^/matka$'},
	{'source': '^/matkalla$'},
	{'source': '^/matkat$'},
	{'source': '^/matkusta$'},
	{'source': '^/meduza$'},
	{'source': '^/meemijatka$'},
	{'source': '^/meemit$'},
	{'source': '^/meidanperhe$'},
	{'source': '^/menaiset$'},
	{'source': '^/mersuforum$'},
	{'source': '^/miesasia$'},
	{'source': '^/miksu$'},
	{'source': '^/millamour$'},
	{'source': '^/minifitness$'},
	{'source': '^/minnakoistinen$'},
	{'source': '^/missmia$'},
	{'source': '^/mobiili-fi$'},
	{'source': '^/mobiilisovellus$'},
	{'source': '^/mongolanssi$'},
	{'source': '^/monna$'},
	{'source': '^/moumou-yp$'},
	{'source': '^/mozgo$'},
	{'source': '^/mrtuomo$'},
	{'source': '^/muistuttaja$'},
	{'source': '^/mungolife$'},
	{'source': '^/mutsie$'},
	{'source': '^/muuttolintuja$'},
	{'source': '^/myprojectisme$'},
	{'source': '^/naag$'},
	{'source': '^/naag-yp$'},
	{'source': '^/naistenpaiva$'},
	{'source': '^/nanaheikkila$'},
	{'source': '^/natalievilen$'},
	{'source': '^/nea-lindberg$'},
	{'source': '^/nellycom$'},
	{'source': '^/nettivinkki$'},
	{'source': '^/nicifit$'},
	{'source': '^/nikonousiainen$'},
	{'source': '^/NR1$'},
	{'source': '^/NR2$'},
	{'source': '^/NR3$'},
	{'source': '^/NR4$'},
	{'source': '^/NR5$'},
	{'source': '^/nu310$'},
	{'source': '^/offerium$'},
	{'source': '^/oliviakumpula$'},
	{'source': '^/onmywayilona$'},
	{'source': '^/orville$'},
	{'source': '^/OSKL$'},
	{'source': '^/ostohyvityksenjoulu$'},
	{'source': '^/pakoarjesta$'},
	{'source': '^/panic$'},
	{'source': '^/parasjoulukalenteri$'},
	{'source': '^/patuemilia$'},
	{'source': '^/pelaajanvalinta$'},
	{'source': '^/pessi$'},
	{'source': '^/pessi-yp$'},
	{'source': '^/pihinainen$'},
	{'source': '^/pinsvsoh$'},
	{'source': '^/pistepirkko$'},
	{'source': '^/pizza$'},
	{'source': '^/placeoflove$'},
	{'source': '^/plan$'},
	{'source': '^/planet49$'},
	{'source': '^/plusmimmi$'},
	{'source': '^/popuptesti$'},
	{'source': '^/postinen$'},
	{'source': '^/priscc$'},
	{'source': '^/proteiinijauhe$'},
	{'source': '^/pykala$'},
	{'source': '^/rahaa-shoppailusta$'},
	{'source': '^/rahantakoja$'},
	{'source': '^/rantapallo$'},
	{'source': '^/ratkaisu$'},
	{'source': '^/rillankoti$'},
	{'source': '^/rockway$'},
	{'source': '^/rokkirekki$'},
	{'source': '^/roni$'},
	{'source': '^/ronjag$'},
	{'source': '^/rtsf$'},
	{'source': '^/ruudun-takaa$'},
	{'source': '^/ruususuu$'},
	{'source': '^/ruutu$'},
	{'source': '^/ruutu2$'},
	{'source': '^/s-lahjakorttidfs3535325$'},
	{'source': '^/samiuotila$'},
	{'source': '^/saralovesyou$'},
	{'source': '^/saralovesyou-yp$'},
	{'source': '^/sarasways$'},
	{'source': '^/seagulls$'},
	{'source': '^/secondhandlife$'},
	{'source': '^/secretluxury$'},
	{'source': '^/seiska$'},
	{'source': '^/sharon$'},
	{'source': '^/sihteeriyhdistys$'},
	{'source': '^/siloposkisusanna$'},
	{'source': '^/singlesday$'},
	{'source': '^/sleepingbeauty$'},
	{'source': '^/slmail$'},
	{'source': '^/smartson$'},
	{'source': '^/soneraetu$'},
	{'source': '^/sonjaissakainen$'},
	{'source': '^/sonnela$'},
	{'source': '^/special$'},
	{'source': '^/sport$'},
	{'source': '^/sportslady$'},
	{'source': '^/spr$'},
	{'source': '^/startliving$'},
	{'source': '^/startup100$'},
	{'source': '^/stockmannfi$'},
	{'source': '^/stuff-about-fitfashion$'},
	{'source': '^/stuunanen$'},
	{'source': '^/sumashopfi$'},
	{'source': '^/suomela$'},
	{'source': '^/suomi24$'},
	{'source': '^/suomiurheilu$'},
	{'source': '^/superdeal$'},
	{'source': '^/superkilpailuttaja$'},
	{'source': '^/syksy$'},
	{'source': '^/synttarit19$'},
	{'source': '^/talooncomtarjous$'},
	{'source': '^/tarina-vaurastumisesta$'},
	{'source': '^/tarjous$'},
	{'source': '^/tarkkamarkka$'},
	{'source': '^/teamarika$'},
	{'source': '^/techblogsuomi$'},
	{'source': '^/teljanneito$'},
	{'source': '^/tervetuloa$'},
	{'source': '^/tervetuloatakaisin$'},
	{'source': '^/test$'},
	{'source': '^/testi123$'},
	{'source': '^/testi12345$'},
	{'source': '^/testi123456$'},
	{'source': '^/testi12345617$'},
	{'source': '^/testi123456607$'},
	{'source': '^/testi456$'},
	{'source': '^/the-realm-of-maria$'},
	{'source': '^/thegoodmorning$'},
	{'source': '^/tiinayli$'},
	{'source': '^/tikis$'},
	{'source': '^/tilausajotnetti$'},
	{'source': '^/tinkerbella$'},
	{'source': '^/top10matkatarjoukset$'},
	{'source': '^/top10matkatarjoukset0219$'},
	{'source': '^/travel$'},
	{'source': '^/triathlon$'},
	{'source': '^/tuplabonus$'},
	{'source': '^/tuplabonusvanha$'},
	{'source': '^/tuplahotelscom$'},
	{'source': '^/tuplazalando$'},
	{'source': '^/tv$'},
	{'source': '^/twiceasnice$'},
	{'source': '^/tyyliametsastamassa$'},
	{'source': '^/tyyliniekka$'},
	{'source': '^/ukkofi$'},
	{'source': '^/unagidon$'},
	{'source': '^/unicornatemysock$'},
	{'source': '^/urheilu$'},
	{'source': '^/uusi$'},
	{'source': '^/uusikuu$'},
	{'source': '^/vaatteet-edullisesti$'},
	{'source': '^/vaatteet-muoti$'},
	{'source': '^/valkoisentalonarkea$'},
	{'source': '^/valokuvaus$'},
	{'source': '^/vauva$'},
	{'source': '^/verkkokauppatestaaja$'},
	{'source': '^/video$'},
	{'source': '^/viihdeelektroniikka$'},
	{'source': '^/viivivalokainen$'},
	{'source': '^/viksuna$'},
	{'source': '^/villafox$'},
	{'source': '^/vilmajarvinen$'},
	{'source': '^/viraalit$'},
	{'source': '^/visio$'},
	{'source': '^/vivian$'},
	{'source': '^/vlogi$'},
	{'source': '^/vlogit$'},
	{'source': '^/voiceoffortuna$'},
	{'source': '^/wae$'},
	{'source': '^/waucher$'},
	{'source': '^/waury$'},
	{'source': '^/wish-aliexpress-ebay-xxxxx$'},
	{'source': '^/wwf$'},
	{'source': '^/yllaty$'},
	{'source': '^/yr$'},
	{'source': '^/ystavanpaiva$'},
	{'source': '^/yves$'},
	{'source': '^/yvesrochertarjous$'},
	{'source': '^/zalandoetu$'},
	{'source': '^/zalandokampanja$'},
	{'source': '^/zalandotarjous$'},
	{'source': '^/api/.+$'},
	{'source': '^/hybridauth.+$'},
	{'source': '^/public/.+$'},
	{'source': '^/static/.+$'},
	{'source': '^/\\.well-known/.+$'},
	{'source': '^/apple-app-site-association$'},
	{'source': '^/robots.txt$'},
	{'source': '^/assets/admin/.+$'},
	{'source': '^/assets/angular/.+$'},
	{'source': '^/assets/build/.+$'},
	{'source': '^/assets/fonts/.+$'},
	{'source': '^/assets/landingPages/.+$'},
	{'source': '^/assets/locales/.+$'},
	{'source': '^/assets/webfonts/.+$'},
	{'source': '^/sitemap\.xml$'},
	{'source': '^/bookingcom'},
	{'source': '^/hotelscom'},
	{'source': '^/stockmann'},
	{'source': '^/ellos'},
	{'source': '^/fitnesstukku'},
	{'source': '^/ebookers'},
	{'source': '^/aliexpress'},
	{'source': '^/nelly'},
	{'source': '^/asos'},
	{'source': '^/cdoncom'},
	{'source': '^/cellbes'},
	{'source': '^/finnish-design-shop'},
	{'source': '^/empfi'},
	{'source': '^/peten-koiratarvike'},
	{'source': '^/zooplus'},
	{'source': '^/bubbleroom'},
	{'source': '^/adlibris'},
	{'source': '^/expedia'},
	{'source': '^/lenson'},
	{'source': '^/rentalcars-com'},
	{'source': '^/house-of-brandon'},
	{'source': '^/eleven-fi'},
	{'source': '^/ferratum'},
	{'source': '^/bangerhead'},
	{'source': '^/lensway'},
	{'source': '^/hotelscombined'},
	{'source': '^/discshop'},
	{'source': '^/yves-rocher'},
	{'source': '^/elisa-viihde'},
	{'source': '^/lehtikuningas-fi'},
	{'source': '^/kaalimato'},
	{'source': '^/elisa-kirja'},
	{'source': '^/rahalaitos-fi'},
	{'source': '^/iittala-fi'},
	{'source': '^/misterspex'},
	{'source': '^/inkclub'},
	{'source': '^/stormberg'},
	{'source': '^/lookfantastic-com'},
	{'source': '^/livbox'},
	{'source': '^/bestseller'},
	{'source': '^/kitchentime'},
	{'source': '^/seiska-lehti'},
	{'source': '^/detur'},
	{'source': '^/agoda'},
	{'source': '^/supersaver'},
	{'source': '^/scandinavian-outdoor'},
	{'source': '^/autonvaraosat24-fi'},
	{'source': '^/coolshop'},
	{'source': '^/myprotein'},
	{'source': '^/feeluniquecom'},
	{'source': '^/reima'},
	{'source': '^/jd-sports'},
	{'source': '^/adidas'},
	{'source': '^/eckero-line'},
	{'source': '^/kodin-kuvalehti'},
	{'source': '^/defshop'},
	{'source': '^/aku-ankka'},
	{'source': '^/keskisen-kello'},
	{'source': '^/nordicfeel'},
	{'source': '^/euro24'},
	{'source': '^/royaldesign-fi'},
	{'source': '^/apteekkituotteet'},
	{'source': '^/caliroots'},
	{'source': '^/biodelly'},
	{'source': '^/shopping4net'},
	{'source': '^/Rum21'},
	{'source': '^/f-secure'},
	{'source': '^/e-villecom'},
	{'source': '^/me-naiset'},
	{'source': '^/junkyard'},
	{'source': '^/Yliopistonverkkoapteekki'},
	{'source': '^/hajuvesi-fi'},
	{'source': '^/smartphoto'},
	{'source': '^/dustin'},
	{'source': '^/spartoo'},
	{'source': '^/grillikauppa-com'},
	{'source': '^/vila-com'},
	{'source': '^/amoma-com'},
	{'source': '^/lomarengas'},
	{'source': '^/prinsessa-lehti'},
	{'source': '^/glorian-ruoka-viini'},
	{'source': '^/yleislaina-fi'},
	{'source': '^/the-body-shop'},
	{'source': '^/vidaxl'},
	{'source': '^/huippukiva'},
	{'source': '^/seksitori'},
	{'source': '^/unisport'},
	{'source': '^/members'},
	{'source': '^/boohoo'},
	{'source': '^/fit-lehti'},
	{'source': '^/stylepit'},
	{'source': '^/porssisahko-fi'},
	{'source': '^/matkapojat'},
	{'source': '^/etua-fi'},
	{'source': '^/blue-tomato'},
	{'source': '^/on24'},
	{'source': '^/swiss-clinic'},
	{'source': '^/reebok'},
	{'source': '^/mylook-fi'},
	{'source': '^/hersecret-fi'},
	{'source': '^/matkavekka'},
	{'source': '^/horze'},
	{'source': '^/koti-ja-keittio'},
	{'source': '^/auto-europe'},
	{'source': '^/nly-man'},
	{'source': '^/kokkiman'},
	{'source': '^/suuri-kasityolehti'},
	{'source': '^/me-naiset-sport'},
	{'source': '^/matkaopas'},
	{'source': '^/only-com'},
	{'source': '^/puhelimenkuoret-fi'},
	{'source': '^/nordic-choice-hotels'},
	{'source': '^/halti-fi'},
	{'source': '^/nordic-green-energy'},
	{'source': '^/autojerry'},
	{'source': '^/hifistudio'},
	{'source': '^/autostarahaa-fi'},
	{'source': '^/meritta-bra'},
	{'source': '^/elle'},
	{'source': '^/sexpartner'},
	{'source': '^/sissos'},
	{'source': '^/mulletoi'},
	{'source': '^/rengas-online-com'},
	{'source': '^/glorian-koti'},
	{'source': '^/tiede-lehti'},
	{'source': '^/hyva-terveys'},
	{'source': '^/aku-ankka-juniori'},
	{'source': '^/qatar-airways'},
	{'source': '^/sexshop'},
	{'source': '^/lehtiapaja'},
	{'source': '^/chain-reaction-cycles'},
	{'source': '^/itunes'},
	{'source': '^/boden'},
	{'source': '^/the-book-depository'},
	{'source': '^/lightinthebox-com'},
	{'source': '^/gearbest'},
	{'source': '^/suojakalvotukku'},
	{'source': '^/digishop'},
	{'source': '^/inkkari'},
	{'source': '^/lelut24'},
	{'source': '^/hotlips'},
	{'source': '^/apollomatkat'},
	{'source': '^/happy-socks'},
	{'source': '^/ikaalisten-matkatoimisto'},
	{'source': '^/nike-com'},
	{'source': '^/lux-case'},
	{'source': '^/banggood'},
	{'source': '^/finink'},
	{'source': '^/autobild'},
	{'source': '^/v8'},
	{'source': '^/lainasto'},
	{'source': '^/chloes'},
	{'source': '^/stayhard'},
	{'source': '^/pilateskauppa'},
	{'source': '^/rellunkulma'},
	{'source': '^/zavvi'},
	{'source': '^/antiikki-design'},
	{'source': '^/hifimaailma'},
	{'source': '^/pelit-lehti'},
	{'source': '^/geo-lehti'},
	{'source': '^/strawberrynet'},
	{'source': '^/dealextreme'},
	{'source': '^/tasapeli-fi'},
	{'source': '^/katso-lehti'},
	{'source': '^/vueling'},
	{'source': '^/kumiukko'},
	{'source': '^/gloria'},
	{'source': '^/yourlenses'},
	{'source': '^/macpiste'},
	{'source': '^/shytobuy'},
	{'source': '^/kilpailuttaja'},
	{'source': '^/tarjouslaina'},
	{'source': '^/rahaneuvos'},
	{'source': '^/luisaviaroma'},
	{'source': '^/superkilpailuttajafi'},
	{'source': '^/hiusverkko'},
	{'source': '^/allbeauty-com'},
	{'source': '^/dhgate'},
	{'source': '^/rosegal'},
	{'source': '^/rose-wholesale'},
	{'source': '^/je-nettiverstas'},
	{'source': '^/microsoft-store'},
	{'source': '^/attitudeclothing'},
	{'source': '^/mprengas-onlinecom'},
	{'source': '^/lufthansa'},
	{'source': '^/superkauppa'},
	{'source': '^/zental'},
	{'source': '^/selected'},
	{'source': '^/footshop'},
	{'source': '^/fragrancedirect'},
	{'source': '^/bulk-powders'},
	{'source': '^/bh-cosmetics'},
	{'source': '^/led-valot'},
	{'source': '^/probikekit-com'},
	{'source': '^/match-com'},
	{'source': '^/mankind'},
	{'source': '^/tm-lewin'},
	{'source': '^/terveinjaloinfi'},
	{'source': '^/findust-com'},
	{'source': '^/akkukauppacom'},
	{'source': '^/jackjones'},
	{'source': '^/pretty-little-thing'},
	{'source': '^/decanter'},
	{'source': '^/panda-feet'},
	{'source': '^/sportsdirect-com'},
	{'source': '^/homeaway'},
	{'source': '^/base-com'},
	{'source': '^/vero-moda'},
	{'source': '^/app-store'},
	{'source': '^/mac-app-store'},
	{'source': '^/hqhair'},
	{'source': '^/dresslily'},
	{'source': '^/naistenverkkokauppafi'},
	{'source': '^/dreamcare'},
	{'source': '^/chi-chi-clothing'},
	{'source': '^/surfdome'},
	{'source': '^/mygeekbox'},
	{'source': '^/365games-co-uk'},
	{'source': '^/finlandiakirja-fi'},
	{'source': '^/kledjut-com'},
	{'source': '^/fotasylum'},
	{'source': '^/echemist'},
	{'source': '^/teekauppa-fi'},
	{'source': '^/yesstyle'},
	{'source': '^/thinkgeek'},
	{'source': '^/lonelyplanetpublications'},
	{'source': '^/wearall-com'},
	{'source': '^/ribble-cycles'},
	{'source': '^/ibookstore'},
	{'source': '^/eqvss'},
	{'source': '^/futurez'},
	{'source': '^/fields-jeweller'},
	{'source': '^/yumi'},
	{'source': '^/karmaloop'},
	{'source': '^/qhotels'},
	{'source': '^/ripsiseerumi'},
	{'source': '^/chaya'},
	{'source': '^/fragrancex'},
	{'source': '^/risicum'},
	{'source': '^/tomtop'},
	{'source': '^/gb-posters'},
	{'source': '^/day-long'},
	{'source': '^/swarovski'},
	{'source': '^/1-like-no-other'},
	{'source': '^/south-beach'},
	{'source': '^/green-people'},
	{'source': '^/juhlaputiikki-ribbon-ink'},
	{'source': '^/merimaailma-sea-life'},
	{'source': '^/bonmarche'},
	{'source': '^/waku-organics'},
	{'source': '^/ebooks-com'},
	{'source': '^/calladream'},
	{'source': '^/ample-bosom'},
	{'source': '^/hotusa'},
	{'source': '^/tb-dress'},
	{'source': '^/charles-wilson'},
	{'source': '^/bondara'},
	{'source': '^/blue-banana'},
	{'source': '^/the-jewel-hut'},
	{'source': '^/the-craft-company'},
	{'source': '^/kylttikeskus-fi'},
	{'source': '^/the-game-collection'},
	{'source': '^/regentrow'},
	{'source': '^/ashley-stewart'},
	{'source': '^/hoteltravel-com'},
	{'source': '^/simply-swim'},
	{'source': '^/fashion-conscience-com'},
	{'source': '^/cycle-surgery'},
	{'source': '^/life-style-sports'},
	{'source': '^/cox-and-cox'},
	{'source': '^/simply-scuba'},
	{'source': '^/cruise'},
	{'source': '^/hyvinvointikauppa'},
	{'source': '^/mytrendyphone'},
	{'source': '^/fellow-finance'},
	{'source': '^/american-golf'},
	{'source': '^/frank-dandy'},
	{'source': '^/cityshopparikortti'},
	{'source': '^/zapals'},
	{'source': '^/proviz'},
	{'source': '^/pretty-polly'},
	{'source': '^/sportamore'},
	{'source': '^/fabriah'},
	{'source': '^/savile-row-company'},
	{'source': '^/urban-surfer'},
	{'source': '^/littlesoho'},
	{'source': '^/van-mildert'},
	{'source': '^/dorothy-perkins'},
	{'source': '^/evans'},
	{'source': '^/sahkomittari'},
	{'source': '^/popreal'},
	{'source': '^/boux-avenue'},
	{'source': '^/shoespie'},
	{'source': '^/prestigia'},
	{'source': '^/gameseek'},
	{'source': '^/arkadia-rahoitus'},
	{'source': '^/audiotukku'},
	{'source': '^/missguided'},
	{'source': '^/dressilyme'},
	{'source': '^/fashion-world'},
	{'source': '^/garden-pharmacy'},
	{'source': '^/unineed'},
	{'source': '^/bluefinance'},
	{'source': '^/yoekcom'},
	{'source': '^/sts-alppimatkat'},
	{'source': '^/eset'},
	{'source': '^/slapiton'},
	{'source': '^/sneapers'},
	{'source': '^/supremebeing'},
	{'source': '^/sourcebmx'},
	{'source': '^/verkkokulta'},
	{'source': '^/svenska-gummihuset'},
	{'source': '^/coggles'},
	{'source': '^/evans-clothing'},
	{'source': '^/aasa'},
	{'source': '^/totes-isotoner'},
	{'source': '^/luinspa'},
	{'source': '^/hotels-click'},
	{'source': '^/homestay-com'},
	{'source': '^/look-book-store'},
	{'source': '^/amazon'},
	{'source': '^/mel-shoes'},
	{'source': '^/kathmandu'},
	{'source': '^/sav-rahoitus'},
	{'source': '^/argento'},
	{'source': '^/divertimenti'},
	{'source': '^/montezumas'},
	{'source': '^/hotelopia'},
	{'source': '^/tackle-direct'},
	{'source': '^/sefton'},
	{'source': '^/byggmax'},
	{'source': '^/muistolaattafi'},
	{'source': '^/seuraajokaisellefi'},
	{'source': '^/chinavasion'},
	{'source': '^/gemondo'},
	{'source': '^/mori'},
	{'source': '^/rebelliousfashion'},
	{'source': '^/junarose'},
	{'source': '^/evisu'},
	{'source': '^/gibson-london'},
	{'source': '^/swerve'},
	{'source': '^/nonnon'},
	{'source': '^/slimming-solutions'},
	{'source': '^/hargroves-cycles'},
	{'source': '^/mybag-com'},
	{'source': '^/sunnyrentals-com'},
	{'source': '^/singapore-airlines'},
	{'source': '^/interhome'},
	{'source': '^/miss-pap'},
	{'source': '^/rosewe'},
	{'source': '^/jonrichard'},
	{'source': '^/easytobook'},
	{'source': '^/pacsun'},
	{'source': '^/dandy-fellow'},
	{'source': '^/joseph-turner'},
	{'source': '^/skatehut'},
	{'source': '^/duracell-direct'},
	{'source': '^/omg-fashion'},
	{'source': '^/golfsupport'},
	{'source': '^/brand-attic'},
	{'source': '^/tumble-tots'},
	{'source': '^/huggler'},
	{'source': '^/hotel-info'},
	{'source': '^/trainer24-fi'},
	{'source': '^/mandco'},
	{'source': '^/trendygolf'},
	{'source': '^/teipparitfi'},
	{'source': '^/forzieri'},
	{'source': '^/amour-london'},
	{'source': '^/vrients'},
	{'source': '^/vestry'},
	{'source': '^/circle-fashion'},
	{'source': '^/racing-green'},
	{'source': '^/apricot'},
	{'source': '^/clickgolf'},
	{'source': '^/ben-sherman'},
	{'source': '^/zocohome'},
	{'source': '^/elibris'},
	{'source': '^/iberostar-hotels'},
	{'source': '^/britannia-hotels'},
	{'source': '^/eto-jeans'},
	{'source': '^/ikrush'},
	{'source': '^/valotikut-fi'},
	{'source': '^/getaroom'},
	{'source': '^/zest-beauty'},
	{'source': '^/brook-taverner'},
	{'source': '^/vivomed-limited'},
	{'source': '^/bianco'},
	{'source': '^/falke'},
	{'source': '^/british-corner-shop'},
	{'source': '^/phonecaseseurope'},
	{'source': '^/minifigures-com'},
	{'source': '^/runners-need'},
	{'source': '^/select-fashion'},
	{'source': '^/painotuotteitafi'},
	{'source': '^/cyclestore'},
	{'source': '^/lomamatkat'},
	{'source': '^/fairy-season'},
	{'source': '^/gossard'},
	{'source': '^/percynobleman'},
	{'source': '^/skoosh'},
	{'source': '^/rapid-online'},
	{'source': '^/quba'},
	{'source': '^/pavers'},
	{'source': '^/outdoorgear'},
	{'source': '^/pakkaustarvikkeita-fi'},
	{'source': '^/fiorellashop'},
	{'source': '^/beauty-expert'},
	{'source': '^/etihad-airways'},
	{'source': '^/kidster'},
	{'source': '^/speedyhen'},
	{'source': '^/proporta'},
	{'source': '^/lorna-jane'},
	{'source': '^/lastminute-com'},
	{'source': '^/gamola-golf'},
	{'source': '^/otelcom'},
	{'source': '^/myvitamins'},
	{'source': '^/hamleys'},
	{'source': '^/new-era'},
	{'source': '^/wallis'},
	{'source': '^/radisson'},
	{'source': '^/Kyboe'},
	{'source': '^/firestar-toys'},
	{'source': '^/ninja'},
	{'source': '^/snow-and-rock'},
	{'source': '^/simply-beach'},
	{'source': '^/lovellsoccer'},
	{'source': '^/nimineula-fi'},
	{'source': '^/taitaentehtyfi'},
	{'source': '^/mastershoe-myshu'},
	{'source': '^/all-outdoor'},
	{'source': '^/hug-bikeshop'},
	{'source': '^/et-terveys'},
	{'source': '^/mamalicious'},
	{'source': '^/laterooms-com'},
	{'source': '^/Catherines'},
	{'source': '^/eachmall'},
	{'source': '^/joules'},
	{'source': '^/perfume-shopping'},
	{'source': '^/joseph-turner-shirts'},
	{'source': '^/uk-Ttghts'},
	{'source': '^/predator-nutrition'},
	{'source': '^/kiinanmuuri-fi'},
	{'source': '^/your-underwear-store'},
	{'source': '^/golf-store-europe'},
	{'source': '^/style-heist'},
	{'source': '^/meli-melo'},
	{'source': '^/marriott'},
	{'source': '^/silver-rush-style'},
	{'source': '^/tokyo-laundry'},
	{'source': '^/scottsdale-golf'},
	{'source': '^/stuarts-london'},
	{'source': '^/smartbuyglasses'},
	{'source': '^/theproteinworks'},
	{'source': '^/allsole'},
	{'source': '^/golfonline'},
	{'source': '^/roboshop'},
	{'source': '^/newfrog-com'},
	{'source': '^/bandcompany'},
	{'source': '^/only-and-sons'},
	{'source': '^/choies'},
	{'source': '^/lahjatnet'},
	{'source': '^/lainafi'},
	{'source': '^/laser24'},
	{'source': '^/beautifulhalo'},
	{'source': '^/tinydeal'},
	{'source': '^/bananashoes'},
	{'source': '^/holiday-inn-express'},
	{'source': '^/coffeedirect-co-uk'},
	{'source': '^/french-connection'},
	{'source': '^/lyle-and-scott'},
	{'source': '^/evolution'},
	{'source': '^/seksilelut-net'},
	{'source': '^/maxishop'},
	{'source': '^/cosmopolitan'},
	{'source': '^/frontmen'},
	{'source': '^/stylein'},
	{'source': '^/vannetimanttifi'},
	{'source': '^/pia-jewellery'},
	{'source': '^/shop4world-com'},
	{'source': '^/lamuscle'},
	{'source': '^/paista-fi'},
	{'source': '^/laihdutusreseptit'},
	{'source': '^/tvc-mall'},
	{'source': '^/aristoc'},
	{'source': '^/jeff-banks'},
	{'source': '^/holiday-autos'},
	{'source': '^/outdoor-look'},
	{'source': '^/zpvit'},
	{'source': '^/urheilutuote-fi'},
	{'source': '^/panda-security'},
	{'source': '^/ateliergs'},
	{'source': '^/marks-and-spencer'},
	{'source': '^/baby-curls'},
	{'source': '^/woolovers'},
	{'source': '^/holiday-inn'},
	{'source': '^/simply-hike'},
	{'source': '^/life-and-looks'},
	{'source': '^/the-watch-hut'},
	{'source': '^/daisy-street'},
	{'source': '^/twinings'},
	{'source': '^/kaiverrus-com'},
	{'source': '^/saaristovartiointi-com'},
	{'source': '^/frezyderm'},
	{'source': '^/zaful'},
	{'source': '^/wool-and-the-gang'},
	{'source': '^/brand-boudoir'},
	{'source': '^/boysstuff'},
	{'source': '^/moss-bros'},
	{'source': '^/milletsports'},
	{'source': '^/the-hut-com'},
	{'source': '^/czech-airlines'},
	{'source': '^/miniinthebox-com'},
	{'source': '^/legoland-windsor'},
	{'source': '^/gti-lehti'},
	{'source': '^/tmart-com'},
	{'source': '^/stuart-weitzman'},
	{'source': '^/fin-yritysrahoitus'},
	{'source': '^/fragrance-expert'},
	{'source': '^/pieces'},
	{'source': '^/hawesandcurtis'},
	{'source': '^/house-of-watches'},
	{'source': '^/tidebuy'},
	{'source': '^/adprint'},
	{'source': '^/tilausajotnet'},
	{'source': '^/simple-dress'},
	{'source': '^/dresslink'},
	{'source': '^/avg'},
	{'source': '^/crowne-plaza'},
	{'source': '^/bad-boy'},
	{'source': '^/aphrodite'},
	{'source': '^/plain-lazy'},
	{'source': '^/weirdfish'},
	{'source': '^/i-want-one-of-those'},
	{'source': '^/matkaporssi'},
	{'source': '^/dfds-seaways'},
	{'source': '^/merkintakeskus'},
	{'source': '^/workwear-express'},
	{'source': '^/helppohinta-fi'},
	{'source': '^/taikapauli-com'},
	{'source': '^/u90soccer-com'},
	{'source': '^/lainaamo'},
	{'source': '^/Berlei'},
	{'source': '^/inderwear'},
	{'source': '^/crew-clothing'},
	{'source': '^/craghoppers'},
	{'source': '^/campingworld'},
	{'source': '^/shein'},
	{'source': '^/cndirect'},
	{'source': '^/Green-Blacks'},
	{'source': '^/fashionmia'},
	{'source': '^/finnish-art-shop'},
	{'source': '^/honor-gold'},
	{'source': '^/sock-shop'},
	{'source': '^/kitbag'},
	{'source': '^/lamp-shop-online'},
	{'source': '^/concept-by-cruise'},
	{'source': '^/insjo'},
	{'source': '^/kaleva-travel'},
	{'source': '^/zefinka'},
	{'source': '^/forever-unique'},
	{'source': '^/repertoire-fashion'},
	{'source': '^/piilola-fi'},
	{'source': '^/wigsbuy'},
	{'source': '^/bellfield'},
	{'source': '^/acycles'},
	{'source': '^/walktall'},
	{'source': '^/consultit-fi'},
	{'source': '^/ege'},
	{'source': '^/toby-tiger'},
	{'source': '^/seksikauppa-fi'},
	{'source': '^/bookbinders-design'},
	{'source': '^/sony-creative-software'},
	{'source': '^/dentaworks'},
	{'source': '^/urheilulehti'},
    {'source': '^/test'},
    {'source': '^/adsasdasd'},
    {'source': '^/sdfgfed'},
    {'source': '^/sdfgfed'},
    {'source': '^/sdfgfed'},
    {'source': '^/sdfgfed'},
    {'source': '^/sdfgfed'},
    {'source': '^/someurl'},
    {'source': '^/afdacas'},
    {'source': '^/afdacas'},
    {'source': '^/afdacas'},
    {'source': '^/afdacas'},
    {'source': '^/afdacas'},
    {'source': '^/afdacas'},
      {'source': '^/afdacas'},
      {'source': '^/afdacas'},
        {'source': '^/afdacas'},
        {'source': '^/afdacas'},
        {'source': '^/Hello from SQS!'},
        {'source': '^/Hello from SQS!'},
        {'source': '^/Hello from SQS!'},
        {'source': '^/Hello from SQS!'},
        {'source': '^/Hello from SQS!'},
        {'source': '^/Hello from SQS!'},
        {'source': '^/Hello from SQS!'},
        {'source': '^/Hello from SQS!'},

	];
	for (let i = 0; i < oldSiteUris.length; i++) {
		let source = new RegExp(oldSiteUris[i].source);
	    if (source.test(request.uri)) {
			request.headers.host[0].value = 'www.bonusway.fi';
			request.origin = {
			custom: {
				domainName: splitDomainName,
				port: 443,
				protocol: 'https',
				path: '',
				sslProtocols: ['TLSv1', 'TLSv1.1', 'TLSv1.2'],
				readTimeout: 5,
				keepaliveTimeout: 5,
				customHeaders: {}
			}
			};
			callback(null, request);
			return;
	    }
	}

  // CRAWLERS -> prerender
  if (typeof request.headers['user-agent'] != 'undefined' && typeof request.headers['user-agent'][0] != 'undefined') {
    if (crawler.test(request.headers['user-agent'][0].value)) {
    	if (!(request.uri.match(/\.(css|webp|jpg|jpeg|png|svg|tff|js|json)$/))) {
	      request.headers.host[0].value = 'www.bonusway.fi';
	      request.headers['x-prerender-token'] = [{ key: 'X-Prerender-Token', value: 'rSoDQvrCMK26o63jGziT'}];
	      request.origin = {
	          custom: {
	              domainName: 'service.prerender.io',
	              port: 443,
	              protocol: 'https',
	              path: '/https%3A%2F%2Fwww.bonusway.fi',
	              sslProtocols: ['TLSv1', 'TLSv1.1', 'TLSv1.2'],
	              readTimeout: 20,
	              keepaliveTimeout: 5,
	              customHeaders: {}
	          }
	      };
	      callback(null, request);
	      return;
    	}
    }
  }

  callback(null, request);   
};
